### ISSUE TITLE
Gems added to every creative tab.

### ISSUE THREAD

**Issue by BBoldt** [elytra/GlassHearts#10]
- GlassHearts-1.12-1.0.62 (build 2 from jenkins)
- Minecraft 1.12
- Forge 2443

![](http://i.imgur.com/g5zj94b.jpg)

**Comment by exaskye** [comment]
i hate 1.12

**Comment by ShetiPhian** [comment]
While working on a bug report I noticed your stuff was spilling over into all tabs, figured I'd help.

There is a now a check that needs to be done before adding the items to the creative tab.
```
@Override
public void getSubItems(CreativeTabs tab, NonNullList<ItemStack> list)
{
    if (isInCreativeTab(tab)) {
        // add the itemstacks to the list here
    }
}
```

**Comment by exaskye** [comment]
I know why this happens. I just think it's stupid and hate it and expressed my discontent.
