### ISSUE TITLE
Glass Heart renderer is hellishly slow

### ISSUE THREAD

**Issue by exaskye** [elytra/GlassHearts#12]
It's not using baked models correctly, and is unpacking them into the psuedo-immediate-mode tessellator.

What to use instead? Model (i.e. the one used in entity rendering)? FastTESR? Get rid of the spinning animation and make it a static block?

**Comment by exaskye** [comment]
Could use completely static rendering (minus fill level) on Fast graphics, disabling the spinning animation.

Fill level needs to become FastTESR, with how often it changes making that part of a static model is, uh, bad. Though, what happens to the additive effect on the buffer? It won't work on a FastTESR. Maybe have both, and use the non-fast TESR if there's buffer lifeforce?

Model from Entity is probably our best bet for the shell since each heart rotates independently.

**Comment by asiekierka** [comment]
@unascribed TileEntity.hasFastRenderer() is dynamic. Charset's pipes already did the trick - if there were any items which used a TEISR (and couldn't be rendered in a FastTESR, obviously), it switched to a slower renderer for that pipe block.

The entity rendering Model will probably be slower than your TESR.

The key thing to do in a FastTESR is either sending vertices directly or rendering IBakedModels or transformed IBakedModels - for transforming, try https://github.com/CharsetMC/Charset/blob/1.12/src/main/java/pl/asie/charset/lib/render/model/ModelTransformer.java

**Comment by asiekierka** [comment]
Also, since you're doing a lot of complex ops to the rendered content (rotation etc), make sure a TESR with display lists/VBOs doesn't end up being faster over a FastTESR.

**Comment by exaskye** [comment]
I thought entity Models used display lists, and unlike FastTESRs didn't have to upload all their vertices every frame. Shouldn't that be faster?

Good to know that hasFastRenderer is dynamic, though.

**Comment by asiekierka** [comment]
@unascribed They do use display lists, but AFAIK they also have a lot of overhead. Not 100% sure on that, though.

You'd be better off making your own display lists/VBOs.

**Comment by exaskye** [comment]
Alright, makes sense. Though you've also reminded me that FastTESRs can't easily do rotation, so I'll probably chicken out and just move the shell rendering to display lists and keep the fill amount as a slow TESR (esp. considering the buffer additive blending plainly doesn't work with a fast tesr; where's premultiplied alpha when you need it??)

**Comment by asiekierka** [comment]
@unascribed "can't easily do" indeed, they have to do it on the CPU! D:
