### ISSUE TITLE
Not a bug—Can I repost the mod？

### ISSUE THREAD

**Issue by forestbat** [elytra/GlassHearts#18]
I‘m a Chinese player and translator on [mcbbs](http://www.mcbbs.net/portal.php)，like your mod very much，but we can't download it from github easily because of GFW（Great Fire Wall），so I want to repost it on mcbbs——we'll claim the mod‘s author is you。

**Comment by exaskye** [comment]
The mod is under the MIT license, which grants unlimited redistribution; go for it.
