### ISSUE TITLE
Crash on server startup

### ISSUE THREAD

**Issue by Not-February** [elytra/GlassHearts#7]
- Mod version: v1.0.0
- Minecraft version: 1.11.2
- Forge version: 13.20.0.2366
- Crash report: https://gist.github.com/Febilian/66fc64f73b9b552102c3efc2e4a3c3db

Doesn't happen when run on just the client. I just put the modpack I'm developing on a dedicated server for testing, and this crash happened before it got very far into loading up.

Let me know if there is more information I can provide.

**Comment by Not-February** [comment]
I poked around a bit and noticed that there's been a commit since the last release that fixed this. I suppose I'll just wait for a new release, whenever that is.

**Comment by exaskye** [comment]
I only release high-quality software

(working on a release, sorry, forgot to, been busy lately)

**Comment by exaskye** [comment]
https://github.com/elytra/GlassHearts/releases/tag/1.11.2-1.0.1
